#language: shell
language: ruby
rvm:
 - 2.2.6
matrix:
env:
    - COVERAGE=1
    - COVERAGE=0
cache:
  directories:
    - $HOME/.m2/repository

before_install:
  - sudo apt-get update -qq

install:
  - gem install coveralls
  - gem install bashcov
  - gem regenerate_binstubs
  - export PATH="$PATH:$PWD:$GEM_PATH:/home/travis/.rvm/gems/ruby-2.2.6/wrappers"
  - sh -e misc/ci-setup.sh

script:
  - sh -e misc/ci-runtest.sh
